spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_boot_mall?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求次数
      stat-view-servlet: #访问监控页面的用户名和密码
        login-username: druid
        login-password: druid
#mybatis:
##  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml
#  configuration: # 指定mybatis全局配置文件中的配置项
#    map-underscore-to-camel-case: true
